[build]
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/plants/*"
  to = "/start-here/"
  status = 301
  force = true

[[redirects]]
  from = "/sprouts/*"
  to = "/start-here/"
  status = 301
  force = true

[[redirects]]
  from = "/start/*"
  to = "/start-here/"
  status = 301
  force = true

[[redirects]]
  from = "/about/*"
  to = "/about-digitally-literate/"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
