[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/plants/*"
  to = "/sprouts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
